services:
  db:
    image: ${PG_IMAGE}
    restart: always
    volumes:
      - db:/var/lib/postgresql/data:Z
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: ${NC_IMAGE}
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - proxy
    networks:
      - proxy-tier
      - default

  cron:
    image: ${NC_IMAGE}
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - certs:/etc/nginx/certs:ro,z
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro
    networks:
      - proxy-tier

#  letsencrypt-companion:
#    image: nginxproxy/acme-companion
#    restart: always
#    volumes:
#      - certs:/etc/nginx/certs:z
#      - acme:/etc/acme.sh:z
#      - vhost.d:/etc/nginx/vhost.d:z
#      - html:/usr/share/nginx/html:z
#      - /var/run/docker.sock:/var/run/docker.sock:z,ro
#    networks:
#      - proxy-tier
#    depends_on:
#      - proxy

# Only for self signed local use. If use this service, disable letsencrypt-companion
  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    env_file:
      - .env
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
